### ISSUE TITLE
Update to latest SDK

### ISSUE THREAD

**Issue by TheAngryByrd** [Krzysztof-Cieslak/FSharp.Analyzers.Sample#2]
When using the nuget package, I'm getting this error message:

```
Unhandled exception. System.MissingMethodException: .ctor
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit)
   at FSharp.Analyzers.SDK.Client.isAnalyzer(MemberInfo mi) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 22
   at FSharp.Analyzers.SDK.Client.analyzerFromMember(MemberInfo mi) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 49
   at FSharp.Analyzers.SDK.Client.analyzersFromType@66.Invoke(MemberInfo mi) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 66
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 179
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at FSharp.Analyzers.SDK.Client.mapping@89-1.Invoke(Type t) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 89
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@273[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 274
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at FSharp.Analyzers.SDK.Client.loadAnalyzers@93.Invoke(Tuple`2 tupledArg) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 94
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at FSharp.Analyzers.SDK.Client.loadAnalyzers(String dir) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.Client.fs:line 99
   at Program.main(String[] argv) in D:\Programowanie\Projekty\FSharp.Analyzers.SDK\src\FSharp.Analyzers.Cli\Program.fs:line 208
```

I can update it to reflect what's in the main SDK repo.

**Comment by Krzysztof-Cieslak** [comment]
Up-to-date sample is directly in SDK repo - https://github.com/ionide/FSharp.Analyzers.SDK/tree/master/samples/OptionAnalyzer

It's also released on NuGet - https://www.nuget.org/packages/OptionAnalyzer/
